plugins {
    alias(libs.plugins.fabric.loom)
}

repositories {
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/'
    }
}

dependencies {
    minecraft libs.minecraft
    mappings loom.officialMojangMappings()
    modImplementation libs.fabric.loader
    modImplementation libs.fabric.api
    modCompileOnly libs.modmenu
    compileOnly libs.jetbrains.annotations
    modImplementation libs.geckolib.fabric

    implementation project(path: ':common', configuration: 'namedElements')
}

sourceSets {
    main {
        resources {
            srcDir project(':common').file('src/main/resources')
        }
    }
}

fabricApi {
    configureDataGeneration()
}

processResources {
    def projectVersion = project.version
    def mcVersion = libs.versions.minecraft.get()
    inputs.property 'version', projectVersion
    inputs.property 'minecraft_version', mcVersion
    filesMatching('fabric.mod.json') {
        expand 'version': projectVersion, 'minecraft_version': mcVersion
    }
}

tasks.named('jar') {
    from(project(':common').sourceSets.main.output)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('sourcesJar') {
    from(project(':common').sourceSets.main.allSource)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
