plugins {
    id 'fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    compileOnly "org.spongepowered:mixin:0.8.5"

    testImplementation "org.junit.jupiter:junit-jupiter:5.10.3"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()
}

loom {
    // Only used to provide Mojang mappings for vanilla classes
}
