plugins {
    alias(libs.plugins.neoforge.moddev)
}

neoForge {
    version = libs.versions.neoforge.get()

    parchment {
        minecraftVersion = libs.versions.parchment.minecraft.get()
        mappingsVersion = libs.versions.parchment.mappings.get()
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', project.file('src/main/generated/').getAbsolutePath(), '--existing', project.file('../common/src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(':common').sourceSets.main
        }
    }
}

sourceSets {
    main {
        resources {
            srcDir project(':common').file('src/main/resources')
        }
    }
}

dependencies {
    compileOnly libs.jetbrains.annotations
    implementation libs.geckolib.neoforge
    implementation project(path: ':common', configuration: 'namedElements')
}

processResources {
    def projectVersion = project.version
    def mcVersion = libs.versions.minecraft.get()
    inputs.property 'version', projectVersion
    inputs.property 'minecraft_version', mcVersion
    filesMatching('META-INF/neoforge.mods.toml') {
        expand 'version': projectVersion, 'minecraft_version': mcVersion
    }
}

tasks.named('jar') {
    from(project(':common').sourceSets.main.output)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('sourcesJar') {
    from(project(':common').sourceSets.main.allSource)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
